dbconfig:
  db_dialect: mysql
  db_host: tcp(127.0.0.1:3306)
  db_name: bee
  db_user: root
  db_password: root
  db_pool_num: 100
  db_config: charset=utf8&parseTime=True&loc=Local
upload:
  default: upload/
  user: upload/user/
  project: upload/project/
web:
  port: 4000
  is_cors: true
cors:
  allow_origin: "*"
  allow_methods:  POST
  allow_headers: Origin,Content-Type
  allow_credentials: true