dbconfig:
  db_dialect: mysql
  db_host: tcp(127.0.0.1:3306)
  db_name: bee
  db_user: root
  db_password: root
  db_config: charset=utf8&parseTime=True&loc=Local
  db_maxopen: 100
  db_maxidle: 10
  db_maxlifetime: 5
upload:
  base: public/
  default: upload/
  user: upload/user/
  project: upload/project/
  team: upload/team/
web:
  port: 4000
  is_cors: true
cors:
  allow_origin: "*"
  allow_methods:  POST
  allow_headers: Origin,Content-Type
  allow_credentials: true
log:
  log_path: log/log/beebe.log
  error_path: log/log/beebe-log.log
  macaron_path: log/log/macaron.log